Repository kalkih/mini-graph-card, pull requests merged in 2019-10, with the labels that each got.

#164 Added url option to tap actions (#160)
  README.md
  src/handleClick.js
Labels: feature request

#165 Group by date and aggregate functions #78 #51
  README.md
  changelog.md
  src/graph.js
  src/main.js
Labels: feature request

#174 Fixed gradient fill bounds (#166)
  src/main.js
  src/style.js
Labels: bug

#172 Support for group by hour
  README.md
  changelog.md
  src/const.js
  src/graph.js
  src/main.js
Labels: feature request

#185 Add support for runtime config updates
  src/const.js
  src/main.js
  src/utils.js
Labels: enhancement

#186 Avoid rendering of additional bars
  src/graph.js
Labels: enhancement

#187 Group by date missing data
  src/graph.js
  src/main.js
Labels: bug
