Repository kalkih/mini-graph-card, pull requests merged in 2020-05, with the labels that each got.

#356 Added clarification as to what "HACS" is
  README.md
Labels: docs

#359 Check for undefined hass before accessing it #358
  src/main.js
Labels: bug

#362 Added value_factor support, to scale value shown in state label
  README.md
  src/buildConfig.js
  src/main.js
Labels: feature request
