Repository kalkih/mini-graph-card, pull requests merged in 2020-04, with the labels that each got.

#325 Reduce white space when extrema isn't enabled #320
  src/main.js
Labels: enhancement

#330 soft_bound config
  README.md
  src/main.js
Labels: feature request

#329 Add delta option in aggregate_func
  src/graph.js
Labels: feature request

#332 Added documentation for 'delta' aggregate function
  README.md
  package.json
  src/graph.js
Labels: docs

#340 typo
  README.md
Labels: docs
